apiVersion: v1
kind: Service
metadata:
  name: pwa
  labels:
    app: pwa
spec:
  ports:
    - port: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: pwa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pwa
  labels:
    app: pwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pwa
  template:
    metadata:
      labels:
        app: pwa
    spec:
      containers:
        - name: pwa
          image: pwa
