name: flowey
services:
  landing:
    build: landing
    develop:
      watch:
        - path: landing
          action: rebuild
    restart: unless-stopped
    networks:
      - landing
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
  backend:
    build: backend
    develop:
      watch:
        - path: backend
          action: rebuild
    restart: unless-stopped
    networks:
      - service
  pwa:
    build: pwa
    develop:
      watch:
        - path: pwa
          action: rebuild
    networks:
      - service
      - traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
networks:
  landing:
    driver: bridge
  service:
    driver: bridge
  traefik:
    external: true
