name: flowey
services:
  landing:
    build: landing
    image: ghcr.io/flowey-org/landing:latest
    develop:
      watch:
        - path: landing
          action: rebuild
    restart: unless-stopped
    networks:
      - landing
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
  backend:
    build: backend
    image: ghcr.io/flowey-org/backend:latest
    develop:
      watch:
        - path: backend
          action: rebuild
    restart: unless-stopped
    networks:
      - service
    volumes:
      - db:/home/flowey/.local/share/flowey
  pwa:
    build: pwa
    image: ghcr.io/flowey-org/pwa:latest
    develop:
      watch:
        - path: pwa
          action: rebuild
    networks:
      - service
      - traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
networks:
  landing:
    driver: bridge
  service:
    driver: bridge
  traefik:
    external: true
volumes:
  db:
