apiVersion: v1
kind: Service
metadata:
  name: landing
  labels:
    app: landing
spec:
  ports:
    - port: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: landing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
  labels:
    app: landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
    spec:
      containers:
        - name: landing
          image: landing
